// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (778531645)
#define NOTOSERIF_14_FONT_ID (-928381217)
#define NOTOSERIF_16_FONT_ID (17214534)
#define NOTOSERIF_18_FONT_ID (840051567)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define SMALL_FONT_ID (1465627787)
#define LIBRON_12_FONT_ID (189239120)
#define LIBRON_14_FONT_ID (1263062637)
#define LIBRON_16_FONT_ID (2031516206)
#define LIBRON_18_FONT_ID (39890387)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LIBRON_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBRON_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBRON_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LIBRON_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
